/**
 * Enumerador para los permisos del sistema.
 * Cada permiso permite gestión completa del módulo correspondiente.
 */
export const PermisoEnum = {
    // Módulos principales del sistema
    GESTIONAR_USUARIOS: 'gestionar_usuarios',
    GESTIONAR_ROLES: 'gestionar_roles',
    GESTIONAR_PERMISOS: 'gestionar_permisos',
    GESTIONAR_CENTROS: 'gestionar_centros',
    GESTIONAR_REGIONALES: 'gestionar_regionales',
    GESTIONAR_PROVINCIAS: 'gestionar_provincias',
    GESTIONAR_CIUDADES: 'gestionar_ciudades',
    GESTIONAR_AREAS: 'gestionar_areas',
    GESTIONAR_DEPENDENCIAS: 'gestionar_dependencias',
    GESTIONAR_COORDINADORES: 'gestionar_coordinadores',
    GESTIONAR_COORDINADORES_GRUPO_MIXTO: 'gestionar_coordinadores_grupo_mixto',
    GESTIONAR_SUPERVISORES: 'gestionar_supervisores',
    GESTIONAR_CARGOS: 'gestionar_cargos',
    GESTIONAR_CDPS: 'gestionar_cdps',
    GESTIONAR_RUBROS: 'gestionar_rubros',
    GESTIONAR_CODIGO_RUBROS: 'gestionar_codigo_rubros',
    GESTIONAR_FUENTES_RECURSOS: 'gestionar_fuentes_recursos',
    GESTIONAR_RESOLUCIONES: 'gestionar_resoluciones',
    GESTIONAR_AUTORIZACIONES: 'gestionar_autorizaciones',
    GESTIONAR_NECESIDAD_CONTRATACION: 'gestionar_necesidad_contratacion',
    GESTIONAR_OBLIGACIONES: 'gestionar_obligaciones',
    GESTIONAR_REGISTROS_PRESUPUESTALES: 'gestionar_registros_presupuestales',

    // Permisos específicos adicionales
    VER_CARGOS: 'ver_cargos',
    CREAR_CARGOS: 'crear_cargos',
    EDITAR_CARGOS: 'editar_cargos',
    CAMBIAR_ESTADO_CARGOS: 'cambiar_estado_cargos',
    VER_CENTROS: 'ver_centros',
    VER_DEPENDENCIAS: 'ver_dependencias',
    CREAR_DEPENDENCIAS: 'crear_dependencias',
    EDITAR_DEPENDENCIAS: 'editar_dependencias',
    VER_CODIGO_RUBROS: 'ver_codigo_rubros',
    CREAR_CODIGO_RUBROS: 'crear_codigo_rubros',
    EDITAR_CODIGO_RUBROS: 'editar_codigo_rubros',
    ELIMINAR_CODIGO_RUBROS: 'eliminar_codigo_rubros',
    VER_COORDINADORES_GRUPO_MIXTO: 'ver_coordinadores_grupo_mixto',
    CREAR_COORDINADORES_GRUPO_MIXTO: 'crear_coordinadores_grupo_mixto',
    EDITAR_COORDINADORES_GRUPO_MIXTO: 'editar_coordinadores_grupo_mixto',
    CAMBIAR_ESTADO_COORDINADORES_GRUPO_MIXTO: 'cambiar_estado_coordinadores_grupo_mixto',
    VER_FUENTES_RECURSOS: 'ver_fuentes_recursos',
    CREAR_FUENTES_RECURSOS: 'crear_fuentes_recursos',
    EDITAR_FUENTES_RECURSOS: 'editar_fuentes_recursos',
    ELIMINAR_FUENTES_RECURSOS: 'eliminar_fuentes_recursos',
    VER_SUPERVISORES: 'ver_supervisores',
    VER_RUBROS: 'ver_rubros',
    VER_PERMISOS: 'ver_permisos',
    CREAR_PERMISOS: 'crear_permisos',
    EDITAR_PERMISOS: 'editar_permisos',
    CAMBIAR_ESTADO_PERMISOS: 'cambiar_estado_permisos',
    VER_ROLES: 'ver_roles',
    CREAR_ROLES: 'crear_roles',

    // Permisos de educación y formación
    GESTIONAR_EDUCACION_FORMAL: 'gestionar_educacion_formal',
    GESTIONAR_EDUCACION_INFORMAL: 'gestionar_educacion_informal',
    GESTIONAR_CERTIFICACIONES: 'gestionar_certificaciones',
    GESTIONAR_EXPERIENCIA_LABORAL: 'gestionar_experiencia_laboral',
    GESTIONAR_INFORMACION_PERSONAL: 'gestionar_informacion_personal',
    GESTIONAR_INFORMACION_PREVIA_CONTRATO: 'gestionar_informacion_previa_contrato',
    GESTIONAR_ESTADO_FORMACIONES: 'gestionar_estado_formaciones',
    GESTIONAR_NIVEL_FORMACION: 'gestionar_nivel_formacion',
    GESTIONAR_TIPO_MINUTA: 'gestionar_tipo_minuta',
    GESTIONAR_REGIMENES_IVA: 'gestionar_regimenes_iva',
    GESTIONAR_INFORMACION_PERSONAL: 'gestionar_informacion_personal',
    GESTIONAR_FORMACIONES_COMPLEMENTARIAS: 'gestionar_formaciones_complementarias',
    GESTIONAR_CLASIFICACION_PERSONA_NATURAL: 'gestionar_clasificacion_persona_natural',
    GESTIONAR_TITULO_FORMACION: 'gestionar_titulo_formacion',

    // Módulos de sistema
    GESTIONAR_CUENTA: 'gestionar_cuenta',
    VER_DASHBOARD: 'ver_dashboard',
};